### ISSUE TITLE
Support for ignoring column definition order?

### ISSUE THREAD

**Issue by zsiegel92** [planetscale/schemadiff#29]
**Feature request**

It would be greatly appreciated if you supported ignoring column definition order.

## Motivation 

Our Planetscale diffs are dominated by many `CREATE TABLE` diffs where columns are re-ordered. This is kind of unavoidable because team members maintain schema changes and when Planetscale merges them and then they apply them to their branch, their branch adds columns in a different order from `main` - I don't think it's fair to expect every migration tool to carry the burden of re-ordering columns, and in fact most do not (Drizzle-kit does not).

## Why I think this is in scope for `schemadiff`

`schemadiff` project already makes an effort to ignore irrelevant schema changes, e.g. in this comment about textual diff:

> The textual diff still works semantically under the hood, and it will ignore trailing comma changes, index reordering, cosntraint name changes, etc.

Furthermore, [the April 2023 Vitesse blog post about `schemadiff`](https://vitess.io/blog/2023-04-24-schemadiff/) kicks this can down the road a few times:

> And, if you want to compute the order in which the changes must take place (some scenarios dictate a specific order, a topic for a future post), then you'd need to solicit confirmation from MySQL by applying changes on the server, iteratively.

> Say we want to determine whether the two have a different set of columns (let's ignore ordering for now). How would we do that?

**note:** I opened a support ticket with Planetscale on this and they referred me to the `schemadiff` blog post and acknowledged that others share my UX issue. This tells me that they would pay attention if `schemadiff` enabled this functionality for them!

**note:** I don't want to make this [an XY problem](https://en.wikipedia.org/wiki/XY_problem#:~:text=The%20XY%20problem%20is%20a,(Y%20or%20Why%3F).) but I propose this could be most easily achieved by first sorting lines inside a `CREATE TABLE` block. Could this be an option in `DiffHints`?

Thank you very much!

**Comment by zsiegel92** [comment]
I realize I probably should have opened this in [the Vitess `schemadiff` repo](https://github.com/vitessio/vitess/tree/main/go/vt/schemadiff) - please let me know if you want me to close and re-open in that repo.

Thanks!

**Comment by dbussink** [comment]
So first of all, the reason that this works the way it works is because column order is meaningful. The most obvious example of that is `select *` where the order of columns returned depends on the order of columns in the table. We want to be really careful about not breaking people's queries, which could happen if ordering is ignored.

If someone has a `select *` query on a dev branch that works fine and then does a DR where in the end the ordering is different and ignored, that `select *` query could likely break on their production branch in very unexpected ways. 

> Our Planetscale diffs are dominated by many `CREATE TABLE` diffs where columns are re-ordered. This is kind of unavoidable because team members maintain schema changes and when Planetscale merges them and then they apply them to their branch, their branch adds columns in a different order from `main` - I don't think it's fair to expect every migration tool to carry the burden of re-ordering columns, and in fact most do not (Drizzle-kit does not).

It highly depends on which tools you look at and what the ecosystem(s) are that you're operating in. Many other tools and ORMs do use `select *` queries which will break if you ignore column ordering, since column ordering is meaningful as mentioned above. Those tools are also order of columns aware and handle it appropriately. At least in my personal opinion, that's also what an ORM or schema management tool should do, as ordering is meaningful and I'd say it's pretty much expected that people will also write their own custom specific queries outside of the ORM using things like `select *`. 

The contextual dependency also means the effort to change this is not isolated to just `schemadiff`. It means that all systems at PlanetScale need to be aware of a user configurable setting for each database, because we cannot change the default for this as this would potentially break many existing users of PlanetScale. Fun fact, we use Ruby on Rails ourselves where ActiveRecord is ordering aware and it also uses `select *`, so we'd never want to enable this for ourselves as it risks breaking queries in unexpected ways. 

So the only option if we decide to support this is to have a user configurable setting that affects quite a few components in the stack, so it's a significant engineering effort beyond just `schemadiff`.

**Comment by zsiegel92** [comment]
Thank you for this thoughtful response @dbussink !

In my support conversation with Planetscale, I noted exactly the `select *` case you mentioned and I understand that column order matters. **

But I'm not actually proposing that Planetscale change how they merge branches, just that they implement a UI to *visualize* a diff in a way that ignores or de-emphasizes re-ordering of columns. Sort of like the "Hide whitespace" option in GitHub's diff view. Their diff visualization stack starts with `schemadiff`, which motivates this request; I made the case that since many ORMs ignore column re-ordering, this is a practical if imperfect way to diff; I also argued that since `schemadiff` supports other quality of life omissions (like order of indices, which probably never affect business logic), this may fit the goals of the project.

@dbussink - can you help me brainstorm how Planetscale might implement this kind of feature, which I think would be great? Maybe they could preprocess schemas by sorting columns before they even use `schemadiff`?


**Note on column order: It appears that several popular ORMs ignore column order: my quick research seemed to show that Drizzle-kit, Prisma, and SQLAlchemy all at least in some cases ignore column order (I have used these three myself). You also mention ORM tools that are aware of column order ("Those tools are also order of columns aware and handle it appropriately."), so even if they use `select *` there may not be confusion on the ORM's side.


Thanks and feel free to close this issue if it's a definite "no"!

**Comment by dbussink** [comment]
> But I'm not actually proposing that Planetscale change how they merge branches, just that they implement a UI to _visualize_ a diff in a way that ignores or de-emphasizes re-ordering of columns.

This is not something we want to do. The diff has meaning and is directly coupled to the DDL statements that are generated. So if we don't want to show a diff, that implies we don't want to generate the DDL statements and the DR should not re-order. 

Having something that does not show a diff, but then does run `ALTER TABLE` operations to re-order is a big no-no for us since it's very surprising and unintuitive behavior. So the only real way to handle this is to make sure it's done consistently. 

> I also argued that since schemadiff supports other quality of life omissions (like order of indices, which probably never affect business logic), this may fit the goals of the project.

Indexes are fundamentally differently, exactly because they have no semantic meaning. It is also not possible to reorder indexes in MySQL therefore as well, unlike columns which can be reordered using `ALTER TABLE`. So that's why these are treated differently and they can't be considered similar to behavior for columns. 

> [@dbussink](https://github.com/dbussink) - can you help me brainstorm how Planetscale might implement this kind of feature, which I think would be great? Maybe they could preprocess schemas by sorting columns before they even use `schemadiff`?

I don't think this is very useful to be honest. This is something that has much more internal considerations that are not really visible to people outside PlanetScale that we need to consider. 

> Thanks and feel free to close this issue if it's a definite "no"!

We're tracking the feedback at the moment, but there's no immediate commitment that we will change anything. So going to close this issue for now then.

**Comment by zsiegel92** [comment]
Thanks for the responses @dbussink 

I may open an issue on Drizzle about re-ordering columns.
